# Generated by Django 4.2.11 on 2025-12-28 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(blank=True, help_text='Author for books, brand for tools/equipment', max_length=200, verbose_name='author/brand')),
                ('isbn', models.CharField(blank=True, help_text='ISBN for books, serial number for equipment', max_length=50, verbose_name='ISBN/Serial Number')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10, verbose_name='condition')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated replacement value in local currency', max_digits=10, null=True, verbose_name='estimated value')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=15, verbose_name='status')),
                ('max_loan_days', models.PositiveIntegerField(default=14, help_text='Maximum number of days this item can be borrowed', verbose_name='maximum loan days')),
                ('requires_deposit', models.BooleanField(default=False, help_text='Whether borrowers need to provide a deposit', verbose_name='requires deposit')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposit amount')),
                ('allow_reservations', models.BooleanField(default=True, help_text="Allow users to reserve this item when it's borrowed", verbose_name='allow reservations')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('borrow_count', models.PositiveIntegerField(default=0, verbose_name='times borrowed')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
                'db_table': 'item_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'item image',
                'verbose_name_plural': 'item images',
                'db_table': 'item_images',
                'ordering': ['order', '-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('notify_when_available', models.BooleanField(default=True, help_text='Send notification when this item becomes available', verbose_name='notify when available')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='items.item', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'wishlist item',
                'verbose_name_plural': 'wishlist items',
                'db_table': 'item_wishlists',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5', verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'item review',
                'verbose_name_plural': 'item reviews',
                'db_table': 'item_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
