# Generated by Django 4.2.11 on 2025-12-28 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_review', to='loans.loan', verbose_name='loan'),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='items.itemcategory', verbose_name='parent category'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.itemcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='item',
            name='current_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_borrowed_items', to=settings.AUTH_USER_MODEL, verbose_name='current borrower'),
        ),
        migrations.AddField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(help_text='Groups where this item is available', related_name='items', to='groups.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddIndex(
            model_name='itemwishlist',
            index=models.Index(fields=['user', 'notify_when_available'], name='item_wishli_user_id_a23208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemwishlist',
            unique_together={('user', 'item')},
        ),
        migrations.AddIndex(
            model_name='itemreview',
            index=models.Index(fields=['item', 'rating'], name='item_review_item_id_d45104_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreview',
            index=models.Index(fields=['reviewer'], name='item_review_reviewe_9ac53b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreview',
            unique_together={('item', 'reviewer', 'loan')},
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['item', 'is_primary'], name='item_images_item_id_0cff34_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='items_slug_71e977_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'is_active'], name='items_owner_i_efdb62_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'is_active'], name='items_status_7c9fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='items_categor_9fd567_idx'),
        ),
    ]
