# Generated by Django 4.2.11 on 2026-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_populate_category_form_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcategory",
            name="form_field_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of field names in display order. Fields not listed will appear after ordered fields. Example: ['title', 'category', 'author', 'description']",
                verbose_name="field order",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("borrowed", "Borrowed"),
                    ("not_right_now", "Not Right Now"),
                    ("special_conditions", "Special Conditions"),
                ],
                default="available",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
