# Generated by Django 4.2.11 on 2025-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher for books', max_length=200, verbose_name='publisher'),
        ),
    ]
