# Generated by Django 4.2.11 on 2025-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the cover was fetched from external API', null=True, verbose_name='cover fetched at'),
        ),
        migrations.AddField(
            model_name='item',
            name='cover_source',
            field=models.CharField(blank=True, choices=[('uploaded', 'User Uploaded'), ('openlibrary', 'Open Library'), ('generated', 'Generated')], help_text='Source of the cover image', max_length=20, verbose_name='cover source'),
        ),
        migrations.AddField(
            model_name='item',
            name='cover_url',
            field=models.URLField(blank=True, help_text='External cover URL from API', verbose_name='cover URL'),
        ),
        migrations.AddField(
            model_name='item',
            name='isbn_lookup_attempted',
            field=models.BooleanField(default=False, help_text="Whether we've tried to look up this ISBN", verbose_name='ISBN lookup attempted'),
        ),
    ]
