# Generated by Django 4.2.11 on 2025-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_cover_fetched_at_item_cover_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='book_format',
            field=models.CharField(blank=True, choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover'), ('ebook', 'E-book'), ('audiobook', 'Audiobook'), ('other', 'Other')], help_text='Format for books', max_length=20, verbose_name='book format'),
        ),
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre for books', max_length=100, verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='item',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages (comma-separated for books)', max_length=200, verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_loan_days',
            field=models.PositiveIntegerField(choices=[(7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month'), (60, '2 months'), (90, '3 months')], default=14, help_text='Maximum number of days this item can be borrowed', verbose_name='maximum loan days'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_right_now', 'Not Right Now'), ('special_conditions', 'Special Conditions')], default='available', max_length=20, verbose_name='status'),
        ),
    ]
