# Generated by Django 4.2.11 on 2025-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_book_format_item_genre_item_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='max_loan_days',
            field=models.PositiveIntegerField(choices=[(1, '1 day'), (3, '3 days'), (7, '1 week'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month'), (60, '2 months'), (90, '3 months')], default=14, help_text='Maximum number of days this item can be borrowed', verbose_name='maximum loan days'),
        ),
    ]
