# Generated by Django 4.2.11 on 2025-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_city_group_country_group_latitude_and_more'),
        ('items', '0006_alter_item_max_loan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this item visible to all users, not just group members', verbose_name='public visibility'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups where this item is available', related_name='items', to='groups.group', verbose_name='groups'),
        ),
    ]
