# Generated by Django 4.2.11 on 2025-12-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_is_public_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='genre',
        ),
        migrations.AddField(
            model_name='item',
            name='subjects',
            field=models.CharField(blank=True, help_text='Subjects/topics for books (comma-separated)', max_length=500, verbose_name='subjects'),
        ),
    ]
