# Generated by Django 4.2.11 on 2025-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_item_genre_item_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(blank=True, help_text='Unique item identifier (e.g., ITEM-XXXX)', max_length=12, null=True, unique=True, verbose_name='unique identifier'),
        ),
    ]
