# Generated by Django 4.2.11 on 2025-12-28 18:41

import random

from django.db import migrations, models


def convert_identifiers(apps, schema_editor):
    """Convert all existing ITEM-XXXXXX identifiers to 10-char alphanumeric format."""
    ALPHANUMERIC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

    # Get Item model
    Item = apps.get_model('items.Item')

    # Get all items with identifiers
    items_with_identifiers = Item.objects.exclude(identifier='')

    converted_count = 0
    for item in items_with_identifiers:
        # Generate new 10-char alphanumeric identifier
        while True:
            new_identifier = ''.join(random.choices(ALPHANUMERIC, k=10))
            # Check if this identifier already exists
            if not Item.objects.filter(identifier=new_identifier).exists():
                break

        # Update the item
        Item.objects.filter(id=item.id).update(identifier=new_identifier)
        converted_count += 1

    # Log the conversion (use print since apps.stdout doesn't work)
    pass


def reverse_convert_identifiers(apps, schema_editor):
    """Rollback: Restore original ITEM-XXXXXX format (best effort)."""
    # This is a best-effort rollback since we can't recover the exact original identifiers
    # We'll generate new ITEM-XXXXXX format identifiers for rollback
    Item = apps.get_model('items.Item')

    for item in Item.objects.all():
        # Generate a new ITEM-XXXXXX identifier for rollback
        chars = ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=6))
        rollback_identifier = f"ITEM-{chars}"

        # Ensure uniqueness for rollback
        while Item.objects.filter(identifier=rollback_identifier).exists():
            chars = ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=6))
            rollback_identifier = f"ITEM-{chars}"

        Item.objects.filter(id=item.id).update(identifier=rollback_identifier)


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_add_identifier_field'),
    ]

    operations = [
        migrations.RunPython(
            convert_identifiers,
            reverse_code=reverse_convert_identifiers
        ),
    ]
