# Generated by Django 4.2.11 on 2026-01-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_populate_form_field_order"),
        ("items", "0013_change_item_public_default"),
    ]

    operations = []
