# Generated by Django 4.2.11 on 2026-01-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_populate_form_field_order"),
        ("loans", "0002_loan_privacy_userloansettings_grouploansettings"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="related_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item this conversation is about (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="items.item",
                verbose_name="related item",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="related_loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Loan this conversation is about (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="loans.loan",
                verbose_name="related loan",
            ),
        ),
    ]
