# Generated by Django 5.2.10 on 2026-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_remove_messaging_encryption_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="encryption_salt",
            field=models.CharField(
                blank=True,
                help_text="Salt used for end-to-end encryption key derivation",
                max_length=100,
                verbose_name="encryption salt",
            ),
        ),
    ]
