# Generated by Django 5.2.10 on 2026-01-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session key for tracking",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="action"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="resource type"
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="resource ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                ("method", models.CharField(max_length=10, verbose_name="HTTP method")),
                ("path", models.TextField(verbose_name="request path")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Additional event details",
                        verbose_name="details",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Previous values for data changes",
                        null=True,
                        verbose_name="old values",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="New values for data changes",
                        null=True,
                        verbose_name="new values",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_logs_ip_addr_932507_idx",
                    ),
                    models.Index(
                        fields=["severity", "timestamp"],
                        name="audit_logs_severit_549d29_idx",
                    ),
                ],
            },
        ),
    ]
