# Generated by Django 4.2.11 on 2025-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city',
            field=models.CharField(default='Unknown', help_text='City where the group is located', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.CharField(default='Germany', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='group',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (auto-filled if possible)', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='group',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (auto-filled if possible)', max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=100, verbose_name='state/region'),
        ),
    ]
