# Generated by Django 4.2.11 on 2026-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_city_group_country_group_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="loan_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden from members"),
                    ("admin_only", "Admins only"),
                    ("public", "Public to members"),
                ],
                default="public",
                help_text="Who can see loans made within this group",
                max_length=15,
                verbose_name="loan visibility",
            ),
        ),
    ]
