# Generated by Django 5.2.10 on 2026-01-14 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_loan_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="comuniza_groups",
                through="groups.GroupMembership",
                through_fields=("group", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
    ]
