# Generated by Django 5.2.10 on 2026-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_privacy_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_email_h_51932d_idx",
            old_name="users_user_email_h_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_usernam_baeb4b_idx",
            old_name="users_user_userna_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_created_30b417_idx",
            old_name="users_user_created_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="email_hash",
            field=models.CharField(
                blank=True,
                help_text="HMAC-SHA256 hash of email for GDPR privacy protection",
                max_length=200,
                verbose_name="email hash",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                help_text="HMAC-SHA256 hash of phone for privacy",
                max_length=200,
                verbose_name="phone hash",
            ),
        ),
    ]
