# Generated by Django 4.2.11 on 2025-12-28 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('loan_completed', 'Loan Completed'), ('item_shared', 'Item Shared'), ('review_given', 'Review Given'), ('group_joined', 'Group Joined'), ('streak_maintained', 'Streak Maintained'), ('threshold_reached', 'Threshold Reached'), ('special_action', 'Special Action')], max_length=20, verbose_name='trigger type')),
                ('threshold_value', models.PositiveIntegerField(blank=True, help_text='Value needed to trigger this achievement', null=True, verbose_name='threshold value')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Additional conditions for earning this achievement', verbose_name='conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'db_table': 'achievements',
                'ordering': ['badge', 'trigger_type'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('badge_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('special', 'Special')], default='bronze', max_length=10, verbose_name='badge type')),
                ('category', models.CharField(choices=[('lending', 'Lending'), ('borrowing', 'Borrowing'), ('community', 'Community'), ('reputation', 'Reputation'), ('special', 'Special')], default='community', max_length=15, verbose_name='category')),
                ('points', models.PositiveIntegerField(default=10, help_text='Reputation points awarded', verbose_name='points')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_secret', models.BooleanField(default=False, help_text='Badge is hidden until earned', verbose_name='secret badge')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'db_table': 'badges',
                'ordering': ['display_order', 'category', 'badge_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='earned at')),
                ('progress', models.PositiveIntegerField(default=100, help_text='Progress percentage for multi-step badges', verbose_name='progress')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional data about how the badge was earned', verbose_name='context data')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='badges.badge', verbose_name='badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user badge',
                'verbose_name_plural': 'user badges',
                'db_table': 'user_badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('bonus', 'Bonus Points'), ('penalty', 'Points Deducted'), ('streak_bonus', 'Streak Bonus'), ('achievement', 'Achievement')], max_length=15, verbose_name='transaction type')),
                ('points', models.IntegerField(verbose_name='points')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('related_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_transactions', to='badges.userbadge', verbose_name='related badge')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_transactions', to='loans.loan', verbose_name='related loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reputation points',
                'verbose_name_plural': 'reputation points',
                'db_table': 'reputation_points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('overall', 'Overall'), ('lending', 'Lending'), ('borrowing', 'Borrowing'), ('reputation', 'Reputation'), ('streak', 'Streak'), ('monthly', 'Monthly')], max_length=15, verbose_name='leaderboard type')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='score')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='rank')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='period end')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'leaderboard',
                'verbose_name_plural': 'leaderboards',
                'db_table': 'leaderboards',
                'ordering': ['leaderboard_type', '-score'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['slug'], name='badges_slug_e14044_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['category', 'is_active'], name='badges_categor_ee62ad_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'is_active'], name='badges_badge_t_8a0f72_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='badges.badge', verbose_name='badge'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'earned_at'], name='user_badges_user_id_9b4c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge', 'earned_at'], name='user_badges_badge_i_0e2a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddIndex(
            model_name='reputationpoints',
            index=models.Index(fields=['user', 'created_at'], name='reputation__user_id_d8c2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='reputationpoints',
            index=models.Index(fields=['transaction_type', 'created_at'], name='reputation__transac_d67851_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', '-score'], name='leaderboard_leaderb_65f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['user', 'leaderboard_type'], name='leaderboard_user_id_5225e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('user', 'leaderboard_type', 'period_start', 'period_end')},
        ),
    ]
