# Generated by Django 4.2.11 on 2025-12-28 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='requested', max_length=15, verbose_name='status')),
                ('request_message', models.TextField(blank=True, help_text='Message from borrower to lender', verbose_name='request message')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='deposit paid')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposit amount')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='deposit returned')),
                ('extension_requested', models.BooleanField(default=False, verbose_name='extension requested')),
                ('extension_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='extension days')),
                ('extension_approved', models.BooleanField(default=False, verbose_name='extension approved')),
                ('extension_reason', models.TextField(blank=True, verbose_name='extension reason')),
                ('condition_at_pickup', models.CharField(blank=True, max_length=100, verbose_name='condition at pickup')),
                ('condition_at_return', models.CharField(blank=True, max_length=100, verbose_name='condition at return')),
                ('damage_reported', models.BooleanField(default=False, verbose_name='damage reported')),
                ('damage_description', models.TextField(blank=True, verbose_name='damage description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', verbose_name='notes')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to=settings.AUTH_USER_MODEL, verbose_name='borrower')),
                ('group', models.ForeignKey(help_text='The group through which this loan was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='groups.group', verbose_name='group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='items.item', verbose_name='item')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_loans', to=settings.AUTH_USER_MODEL, verbose_name='lender')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_lent', models.PositiveIntegerField(default=0, verbose_name='items lent')),
                ('lending_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as a lender (0-5)', max_digits=3, verbose_name='lending rating')),
                ('items_borrowed', models.PositiveIntegerField(default=0, verbose_name='items borrowed')),
                ('borrowing_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as a borrower (0-5)', max_digits=3, verbose_name='borrowing rating')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Combined average rating (0-5)', max_digits=3, verbose_name='overall rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('on_time_returns', models.PositiveIntegerField(default=0, verbose_name='on-time returns')),
                ('late_returns', models.PositiveIntegerField(default=0, verbose_name='late returns')),
                ('cancellations', models.PositiveIntegerField(default=0, verbose_name='cancellations')),
                ('trust_score', models.PositiveIntegerField(default=50, help_text='Algorithmic trust score from 0-100', verbose_name='trust score')),
                ('verified', models.BooleanField(default=False, verbose_name='verified user')),
                ('top_lender', models.BooleanField(default=False, verbose_name='top lender badge')),
                ('reliable_borrower', models.BooleanField(default=False, verbose_name='reliable borrower badge')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user reputation',
                'verbose_name_plural': 'user reputations',
                'db_table': 'user_reputations',
            },
        ),
        migrations.CreateModel(
            name='LoanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('lender', 'Lender'), ('borrower', 'Borrower')], help_text='Whether the reviewer was the lender or borrower', max_length=10, verbose_name='reviewer role')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5', verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('communication_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='communication')),
                ('reliability_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='reliability')),
                ('condition_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='For lender: item returned condition. For borrower: item received condition', verbose_name='item condition')),
                ('would_lend_again', models.BooleanField(default=True, verbose_name='would lend/borrow again')),
                ('is_public', models.BooleanField(default=True, verbose_name='public review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='loans.loan', verbose_name='loan')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='reviewee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'loan review',
                'verbose_name_plural': 'loan reviews',
                'db_table': 'loan_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewee', 'is_public'], name='loan_review_reviewe_6e7c52_idx'), models.Index(fields=['loan'], name='loan_review_loan_id_ecf3fc_idx')],
                'unique_together': {('loan', 'reviewer')},
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_borrowe_6654de_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['lender', 'status'], name='loans_lender__713c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['item', 'status'], name='loans_item_id_20b73c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='loans_status_ca3b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['group', 'status'], name='loans_group_i_20ca01_idx'),
        ),
    ]
