# Generated by Django 4.2.11 on 2026-01-02 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0003_group_loan_visibility"),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("participants", "Participants only"),
                    ("group_admins", "Group admins can view"),
                    ("group_public", "Visible to group members"),
                ],
                default="participants",
                help_text="Who can view this loan",
                max_length=15,
                verbose_name="privacy",
            ),
        ),
        migrations.CreateModel(
            name="UserLoanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_loan_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Default number of days for loans",
                        verbose_name="default loan days",
                    ),
                ),
                (
                    "allow_extensions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether borrower can request extensions",
                        verbose_name="allow extensions",
                    ),
                ),
                (
                    "require_approval_for_extensions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether extensions require approval or are automatic",
                        verbose_name="require approval for extensions",
                    ),
                ),
                (
                    "max_extension_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Maximum days that can be requested for extension",
                        verbose_name="maximum extension days",
                    ),
                ),
                (
                    "default_loan_privacy",
                    models.CharField(
                        choices=[
                            ("participants", "Participants only"),
                            ("group_admins", "Group admins can view"),
                            ("group_public", "Visible to group members"),
                        ],
                        default="participants",
                        help_text="Default visibility for new loans",
                        max_length=15,
                        verbose_name="default loan privacy",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for loan activities",
                        verbose_name="email notifications",
                    ),
                ),
                (
                    "message_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive in-app message notifications",
                        verbose_name="message notifications",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user loan settings",
                "verbose_name_plural": "user loan settings",
                "db_table": "user_loan_settings",
            },
        ),
        migrations.CreateModel(
            name="GroupLoanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days for loans in this group (null = use global setting)",
                        null=True,
                        verbose_name="loan days",
                    ),
                ),
                (
                    "allow_extensions",
                    models.BooleanField(
                        blank=True,
                        help_text="Allow extensions in this group (null = use global setting)",
                        null=True,
                        verbose_name="allow extensions",
                    ),
                ),
                (
                    "require_approval_for_extensions",
                    models.BooleanField(
                        blank=True,
                        help_text="Extensions require approval in this group (null = use global setting)",
                        null=True,
                        verbose_name="require approval for extensions",
                    ),
                ),
                (
                    "max_extension_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum extension days in this group (null = use global setting)",
                        null=True,
                        verbose_name="maximum extension days",
                    ),
                ),
                (
                    "loan_privacy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("participants", "Participants only"),
                            ("group_admins", "Group admins can view"),
                            ("group_public", "Visible to group members"),
                        ],
                        help_text="Visibility for loans in this group (blank = use global setting)",
                        max_length=15,
                        verbose_name="loan privacy",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_loan_settings",
                        to="groups.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_loan_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "group loan settings",
                "verbose_name_plural": "group loan settings",
                "db_table": "group_loan_settings",
                "indexes": [
                    models.Index(
                        fields=["user", "group"], name="group_loan__user_id_ad8e38_idx"
                    )
                ],
                "unique_together": {("user", "group")},
            },
        ),
    ]
