# Generated by Django 4.2.27 on 2026-01-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_privacy_userloansettings_grouploansettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('borrower_returned', 'Borrower Returned'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='requested', max_length=20, verbose_name='status'),
        ),
    ]
