# Generated by Django 4.2.27 on 2026-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('loan_request', 'Loan Request'), ('loan_approved', 'Loan Approved'), ('loan_pickup', 'Item Picked Up'), ('loan_returned', 'Item Returned'), ('loan_rejected', 'Loan Rejected'), ('loan_extension_request', 'Extension Request'), ('loan_extension_decision', 'Extension Decision'), ('loan_overdue', 'Loan Overdue'), ('review_received', 'Review Received')], default='message', max_length=20, verbose_name='type'),
        ),
    ]
