# Generated by Django 5.2.10 on 2026-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "New Message"),
                    ("loan_request", "Loan Request"),
                    ("loan_approved", "Loan Approved"),
                    ("loan_pickup", "Item Picked Up"),
                    ("loan_return_initiated", "Return Initiated"),
                    ("loan_returned", "Item Returned"),
                    ("loan_rejected", "Loan Rejected"),
                    ("loan_extension_request", "Extension Request"),
                    ("loan_extension_decision", "Extension Decision"),
                    ("loan_overdue", "Loan Overdue"),
                    ("review_received", "Review Received"),
                ],
                default="message",
                max_length=25,
                verbose_name="type",
            ),
        ),
    ]
